### ISSUE TITLE
Contributions guideline

### ISSUE THREAD

**Issue by somas95** [oTree-org/oTree#105]
Hi. I'd like to know if otree is open to external contributions, and if so, what're the guidelines to do so, (i.e, would you accept merge requests upfront, or would you rather discuss functionality previously on issues?).

Related to that is the question if the repo should be taken as upstream, since it seems pypi is distributing more up to date code than what the repo holds.

Thanks for your help

**Comment by oTree-org** [comment]
Hi, thank you for the interest!

For the otree-core project, the best way to start is with a discussion of the proposed functionality. Feel free to email me (chris@otree.org) or open an issue. Once we have agreed on a design, then merging in the changes through git etc will be the easy part :)

For other projects like those pinned on my GitHub page (https://github.com/oTree-org/), the process is a bit more relaxed. These projects (such as oTree HR) have a more straightforward codebase for newcomers to understand and I am actively looking for contributors since they are newer projects.

**Comment by somas95** [comment]
Thanks! I'll be opening some issues in otree-core soon
