### ISSUE TITLE
Report float numbers in result page of "Public Goods (simple version)"

### ISSUE THREAD

**Issue by itsaquestion** [oTree-org/oTree#45]
HI! 
I just played the "Public Goods (simple version from tutorial)" in demo, and I found that the result page always reports payoffs as integer, even if the actual payoff should be a float number.

e.g. three player contribute 1, 2, 3 points respectively, so each player gets (1+2+3)*1.8/3 = 3.6, and the payoffs should be 102.6, 101.6, 100.6 points respectively, but the result page report those as 103, 102,101 points.

so why? and how can I show the payoffs as a float?

Thanks.

**Comment by oTree-org** [comment]
This is part of the design of the "points" currency, because some people prefer for it to be an integer (e.g. for simplicity). If you set `USE_POINTS = False`, then the "real world" currency will be formatted with 2 decimal places. Or you can use `FloatField` or `DecimalField`.

I logged a separate issue here to allow the "points" currency to have decimal places: https://github.com/oTree-org/otree-core/issues/350
