### ISSUE TITLE
`Player.start()` equivalent missing in oTree 5

### ISSUE THREAD

**Issue by JKRhb** [oTree-org/oTree#99]
Trying out the new oTree format I noticed that there seems to be no equivalent for the `Player.start()` method yet. Do you plan on adding this to the new version?

(By the way, I think the new format simplifies things a lot so thank you for making this large step forward!)

**Comment by oTree-org** [comment]
Hi, I don't plan on adding start(). It was in beta during oTree 3, but I found its implementation was too complex.

(Thank you for the nice words BTW :))

**Comment by JKRhb** [comment]
> Hi, I don't plan on adding start(). It was in beta during oTree 3, but I found its implementation was too complex.

It is a bit late, but thank you for your response! It is a bit sad that this function is missing as it has provided a very elegant solution for some use cases for me in oTree 3.

I was wondering if there could be a function like `before_this_page` to take its place that gets executed the first time a page is displayed? Otherwise I assume you need to move code that is supposed to be executed before the first page of an app to its predecessor in which I see a potential problem if the app sequence should change.

> (Thank you for the nice words BTW :))

Credit where credit is due :)

**Comment by oTree-org** [comment]
Hi, yes I agree it can be tricky. The reason I didn't include this feature in v5 is that while it's simple in concept, the implementation had a number of corner-cases that made the code more complex. (Same thing with a before_this_page function.) So, rather than making a general solution for this, I decided it's better for people to pick whichever of the following solutions works best for them:

(a) Use before_next_page on the previous page

(b) Use is_displayed or vars_for_template on the current page

**Comment by JKRhb** [comment]
Thank you once again for your helpful reponse!

> Hi, yes I agree it can be tricky. The reason I didn't include this feature in v5 is that while it's simple in concept, the implementation had a number of corner-cases that made the code more complex. (Same thing with a before_this_page function.) 

I see, that is totally understandable. I might have a bit of an edge case that requires some initialization (that should only happen once) when a player enters the app  which `start()` has been very handy for. However, using `is_displayed`  is a good idea that I will try out :)
